/**
 * Shared character code constants used across the parser, streaming parser,
 * writer, and converters.
 *
 * Using named constants instead of magic numbers improves readability and
 * catches typos at compile time. The SCREAMING_CASE convention follows the
 * standard practice for numeric constants.
 *
 * AUTO-GENERATED by scripts/generate-char-codes.ts — do not edit by hand.
 */

// --- Brackets and delimiters ---
export const LT = 60; // <
export const GT = 62; // >
export const SLASH = 47; // /
export const BANG = 33; // !
export const QUESTION = 63; // ?
export const EQ = 61; // =
export const LBRACKET = 91; // [
export const RBRACKET = 93; // ]

// --- Quotes ---
export const SQUOTE = 39; // '
export const DQUOTE = 34; // "

// --- Whitespace ---
export const TAB = 9; // \t
export const LF = 10; // \n
export const CR = 13; // \r
export const SPACE = 32; // (space)

// --- Punctuation ---
export const DASH = 45; // -
export const UNDERSCORE = 95; // _
export const COLON = 58; // :
export const DOLLAR = 36; // $

// --- CDATA signature characters: <![CDATA[ ---
export const UPPER_C = 67; // C
export const UPPER_D = 68; // D
export const UPPER_A = 65; // A
export const UPPER_T = 84; // T
