/**
 * Generates src/utilities/charCodes.ts from a declarative list of
 * { name, character } entries grouped into sections.
 *
 * Usage:
 *   npx tsx scripts/generate-char-codes.ts
 *
 * To add a new character code constant:
 *   1. Add an entry to the appropriate section below (or create a new section).
 *   2. Run this script.
 *   3. The generated file is written to src/utilities/charCodes.ts.
 */

import { writeFileSync } from "node:fs";
import { resolve, dirname } from "node:path";
import { fileURLToPath } from "node:url";

// ---------------------------------------------------------------------------
// Configuration — add/remove/reorder entries here
// ---------------------------------------------------------------------------

interface CharCodeEntry {
  /** SCREAMING_CASE constant name */
  name: string;
  /** The character whose charCodeAt(0) produces the value */
  character: string;
}

interface CharCodeSection {
  /** Section comment label */
  label: string;
  entries: CharCodeEntry[];
}

const sections: CharCodeSection[] = [
  {
    label: "Brackets and delimiters",
    entries: [
      { name: "LT", character: "<" },
      { name: "GT", character: ">" },
      { name: "SLASH", character: "/" },
      { name: "BANG", character: "!" },
      { name: "QUESTION", character: "?" },
      { name: "EQ", character: "=" },
      { name: "LBRACKET", character: "[" },
      { name: "RBRACKET", character: "]" },
    ],
  },
  {
    label: "Quotes",
    entries: [
      { name: "SQUOTE", character: "'" },
      { name: "DQUOTE", character: '"' },
    ],
  },
  {
    label: "Whitespace",
    entries: [
      { name: "TAB", character: "\t" },
      { name: "LF", character: "\n" },
      { name: "CR", character: "\r" },
      { name: "SPACE", character: " " },
    ],
  },
  {
    label: "Punctuation",
    entries: [
      { name: "DASH", character: "-" },
      { name: "UNDERSCORE", character: "_" },
      { name: "COLON", character: ":" },
      { name: "DOLLAR", character: "$" },
    ],
  },
  {
    label: "CDATA signature characters: <![CDATA[",
    entries: [
      { name: "UPPER_C", character: "C" },
      { name: "UPPER_D", character: "D" },
      { name: "UPPER_A", character: "A" },
      { name: "UPPER_T", character: "T" },
    ],
  },
];

// ---------------------------------------------------------------------------
// Generation
// ---------------------------------------------------------------------------

/** Format a character as a readable inline comment (e.g. `// <` or `// \t`). */
function formatCharacterComment(character: string): string {
  const escapeMap: Record<string, string> = {
    "\t": "\\t",
    "\n": "\\n",
    "\r": "\\r",
    " ": "(space)",
  };
  return escapeMap[character] ?? character;
}

function generate(): string {
  const lines: string[] = [];

  lines.push("/**");
  lines.push(" * Shared character code constants used across the parser, streaming parser,");
  lines.push(" * writer, and converters.");
  lines.push(" *");
  lines.push(" * Using named constants instead of magic numbers improves readability and");
  lines.push(" * catches typos at compile time. The SCREAMING_CASE convention follows the");
  lines.push(" * standard practice for numeric constants.");
  lines.push(" *");
  lines.push(" * AUTO-GENERATED by scripts/generate-char-codes.ts — do not edit by hand.");
  lines.push(" */");

  for (const section of sections) {
    lines.push("");
    lines.push(`// --- ${section.label} ---`);
    for (const entry of section.entries) {
      const code = entry.character.charCodeAt(0);
      const comment = formatCharacterComment(entry.character);
      lines.push(`export const ${entry.name} = ${code}; // ${comment}`);
    }
  }

  lines.push("");
  return lines.join("\n");
}

// ---------------------------------------------------------------------------
// Write
// ---------------------------------------------------------------------------

const scriptDirectory = dirname(fileURLToPath(import.meta.url));
const outputPath = resolve(scriptDirectory, "..", "src", "utilities", "charCodes.ts");
const content = generate();

writeFileSync(outputPath, content, "utf-8");

const totalConstants = sections.reduce((sum, section) => sum + section.entries.length, 0);
console.log(`Wrote ${totalConstants} character code constants to ${outputPath}`);
